### ISSUE TITLE
Cannot install v1.7 on Laravel 7

### ISSUE THREAD

**Issue by vanushwashere** [stechstudio/laravel-env-security#15]
I get this error because in 1.7 version commit in composer.json is required ` "illuminate/support": "5.*"` and ` "illuminate/console": "5.*",` but they should be **7.***.
Also I noticed that you fixed that on **master** branch, so please release a fixed version 
![image](https://user-images.githubusercontent.com/24995381/87245974-09943f80-c45b-11ea-9600-fb8f1b2cf9a5.png)

**Comment by jszobody** [comment]
Weird. v1.6 had the latest composer file, but then v1.7 doesn't. I screwed up v1.7 somehow, apparently. 

Just tagged v1.8, should resolve this.
