### ISSUE TITLE
 InvalidArgumentException  : Found 2 errors while validating the input provided for the Encrypt operation: [KeyId] is missing and is a required parameter [KeyId] expected string length to be >= 1, but found string length of 0

### ISSUE THREAD

**Issue by prasadguptapankaj** [stechstudio/laravel-env-security#29]
InvalidArgumentException  : Found 2 errors while validating the input provided for the Encrypt operation:
[KeyId] is missing and is a required parameter
[KeyId] expected string length to be >= 1, but found string length of 0

**Comment by jszobody** [comment]
Sounds like you're missing config, yeah? This would make this the same issue you mentioned in #28 where all your package config is null.

I'm not sure how to help you. You need to troubleshoot why config values aren't present. And it might be something related to your old version of Laravel. If you were to create a fresh Laravel 10 app real quick, install this package, and have the same problem I would be very interested to hear.
