### ISSUE TITLE
What is the purpose of src/Console/Files/* ?

### ISSUE THREAD

**Issue by mskenderian-wps** [stechstudio/laravel-env-security#5]
what is the purpose of the files in src/Console/Files/ ?

this is a great idea. i love the package.

**Comment by jszobody** [comment]
Hmm Console/Files wasn't supposed to be on master branch yet. It's non-functional at the moment. 

Glad this package is useful! 👍

**Comment by mskenderian-wps** [comment]
AHH makes more sense.
